/* Firewall 3D — real malware from history, after Wikipedia's
 * "Timeline of computer viruses and worms":
 * https://en.wikipedia.org/wiki/Timeline_of_computer_viruses_and_worms
 *
 * Every monster in the game is named after one of these, chosen from the
 * entries whose `kind` matches it (virus, worm, trojan, spyware, ransomware,
 * rootkit). The threat database lists them all as a timeline and ticks off
 * the ones the player has removed. Keep the entries in date order.
 */
const FW_HISTORY = [
  { year: 1971, name: "Creeper", kind: "worm",
    en: "An experimental self-copying program on ARPANET, the Internet's ancestor. It hopped between computers printing \"I'M THE CREEPER: CATCH ME IF YOU CAN.\" A program called Reaper was written to delete it.",
    zh: "ARPANET（互联网的前身）上的一个实验性自我复制程序。它在计算机之间跳来跳去，并显示“I'M THE CREEPER: CATCH ME IF YOU CAN.”。后来有人写了一个叫 Reaper 的程序专门删除它。" },
  { year: 1982, name: "Elk Cloner", kind: "virus",
    en: "One of the first viruses to spread outside a lab. It travelled on Apple II floppy disks through the boot sector and showed a short poem on every 50th boot.",
    zh: "最早在实验室之外传播的病毒之一。它通过引导扇区在 Apple II 软盘之间传播，每启动 50 次就显示一首小诗。" },
  { year: 1986, name: "Brain", kind: "virus",
    en: "The first virus for IBM PCs, written by two brothers in Lahore, Pakistan. It infected the boot sector of floppy disks.",
    zh: "第一个感染 IBM PC 的病毒，由巴基斯坦拉合尔的两兄弟编写。它感染软盘的引导扇区。" },
  { year: 1988, name: "Morris worm", kind: "worm",
    en: "Released on 2 November 1988, it used Unix security holes and weak passwords to slow or crash around 6,000 computers, about a tenth of the Internet at the time. Its author was the first person convicted under the US Computer Fraud and Abuse Act.",
    zh: "1988 年 11 月 2 日释放，利用 Unix 安全漏洞和弱密码，拖慢或搞垮了约 6000 台计算机，约占当时互联网的十分之一。作者成为第一个依据美国《计算机欺诈和滥用法》被定罪的人。" },
  { year: 1989, name: "AIDS Trojan", kind: "ransomware",
    en: "Posted out on floppy disks labelled as AIDS information. After a number of reboots it hid and scrambled the names of files and demanded $189. It is the first known ransomware.",
    zh: "以艾滋病资料的名义通过软盘邮寄。重启若干次后，它会隐藏并打乱文件名，索要 189 美元。这是已知最早的勒索软件。" },
  { year: 1992, name: "Michelangelo", kind: "virus",
    en: "A boot-sector virus set to overwrite data on 6 March, Michelangelo's birthday. News reports predicted millions of victims; far fewer were hit, but it made many people buy antivirus software for the first time.",
    zh: "一种引导扇区病毒，设定在 3 月 6 日（米开朗基罗的生日）覆盖数据。媒体预测会有数百万受害者，实际少得多，但它让很多人第一次购买了杀毒软件。" },
  { year: 1998, name: "CIH (Chernobyl)", kind: "virus",
    en: "Overwrote files and, on some machines, the BIOS chip, leaving the PC unable to start at all. It was set to trigger on 26 April.",
    zh: "覆盖文件，并在部分机器上改写 BIOS 芯片，使电脑完全无法启动。它设定在 4 月 26 日发作。" },
  { year: 1999, name: "Melissa", kind: "virus",
    en: "A macro virus hidden in a Word document. Opening it emailed the document to the first 50 people in your Outlook address book, flooding mail servers.",
    zh: "藏在 Word 文档里的宏病毒。打开后，它会把文档发给 Outlook 通讯录里的前 50 个人，导致邮件服务器瘫痪。" },
  { year: 2000, name: "ILOVEYOU", kind: "worm",
    en: "Arrived as an email attachment called LOVE-LETTER-FOR-YOU.TXT.vbs. Opening it overwrote files and mailed the worm to every contact, and it reached tens of millions of Windows PCs within days.",
    zh: "以名为 LOVE-LETTER-FOR-YOU.TXT.vbs 的邮件附件出现。打开后它会覆盖文件并把自己发给所有联系人，几天内就传到了数千万台 Windows 电脑。" },
  { year: 2001, name: "Code Red", kind: "worm",
    en: "Attacked Microsoft IIS web servers and defaced websites with \"Hacked By Chinese!\". More than 350,000 servers were infected in a single day.",
    zh: "攻击微软 IIS 网页服务器，把网站篡改为“Hacked By Chinese!”。一天之内就有超过 35 万台服务器被感染。" },
  { year: 2003, name: "SQL Slammer", kind: "worm",
    en: "A tiny 376-byte worm that attacked Microsoft SQL Server. It infected most of its roughly 75,000 victims within ten minutes and slowed Internet traffic around the world.",
    zh: "一个只有 376 字节的小蠕虫，攻击微软 SQL Server。它在十分钟内感染了约 7.5 万个受害者中的大部分，拖慢了全球的互联网流量。" },
  { year: 2003, name: "Blaster", kind: "worm",
    en: "Spread through a flaw in Windows' RPC service and made infected PCs shut down and restart over and over. A fix had been published weeks earlier: patching matters.",
    zh: "通过 Windows RPC 服务的漏洞传播，让被感染的电脑反复关机重启。修复补丁早在几周前就已发布——及时打补丁很重要。" },
  { year: 2004, name: "MyDoom", kind: "worm",
    en: "An email worm that became the fastest-spreading of its time, and used the PCs it infected to flood websites in denial-of-service attacks.",
    zh: "当时传播最快的邮件蠕虫，并利用被感染的电脑发动拒绝服务攻击，淹没目标网站。" },
  { year: 2004, name: "Cabir", kind: "mobile",
    en: "The first known worm for mobile phones. It spread between Nokia phones running Symbian over Bluetooth and showed the word \"Caribe\" on the screen. It was a proof of concept that did little harm, but it showed phones could be infected too.",
    zh: "已知第一个手机蠕虫。它通过蓝牙在运行 Symbian 系统的诺基亚手机之间传播，并在屏幕上显示“Caribe”。它只是概念验证，危害不大，但证明了手机同样会被感染。" },
  { year: 2005, name: "Sony BMG rootkit", kind: "rootkit",
    en: "Copy-protection software on music CDs quietly installed a rootkit that hid itself from Windows, and other malware could use it to hide too. Sony recalled the CDs.",
    zh: "音乐 CD 上的防复制软件悄悄安装了一个 Rootkit，把自己从 Windows 中隐藏起来，其他恶意软件也能借它隐身。索尼最终召回了这些 CD。" },
  { year: 2007, name: "Storm Worm", kind: "trojan",
    en: "Despite its name, a Trojan. Emails with headlines such as \"230 dead as storm batters Europe\" tricked people into running it, and each infected PC joined a huge botnet.",
    zh: "名字叫蠕虫，其实是木马。标题像“风暴袭击欧洲，230 人死亡”的邮件诱骗人们运行它，每台被感染的电脑都会加入一个庞大的僵尸网络。" },
  { year: 2007, name: "Zeus", kind: "spyware",
    en: "Logged keystrokes and stole online-banking passwords from millions of PCs, sending them to criminals. Its code was later leaked and reused in many other banking Trojans.",
    zh: "记录键盘输入，从数百万台电脑上窃取网上银行密码并发给犯罪分子。它的源代码后来泄露，被许多其他银行木马重复使用。" },
  { year: 2008, name: "Conficker", kind: "worm",
    en: "Spread through a Windows flaw, weak passwords and USB drives, infecting millions of computers in homes, businesses and governments.",
    zh: "通过 Windows 漏洞、弱密码和 U 盘传播，感染了家庭、企业和政府的数百万台计算机。" },
  { year: 2010, name: "Stuxnet", kind: "rootkit",
    en: "A worm built to sabotage uranium-enrichment centrifuges in Iran by reprogramming Siemens industrial controllers. It used several unknown (zero-day) flaws and rootkits to stay hidden.",
    zh: "一种专门用来破坏伊朗铀浓缩离心机的蠕虫，它会篡改西门子工业控制器的程序。它利用了多个未公开的（零日）漏洞，并用 Rootkit 隐藏自己。" },
  { year: 2012, name: "Flame", kind: "spyware",
    en: "Espionage malware found on computers in the Middle East. It could record audio from the microphone, take screenshots and log keystrokes.",
    zh: "在中东地区计算机上发现的间谍恶意软件。它能通过麦克风录音、截取屏幕并记录键盘输入。" },
  { year: 2012, name: "Shamoon", kind: "wiper",
    en: "Wiped the data on about 30,000 computers at the oil company Saudi Aramco, overwriting files with part of an image of a burning American flag. The company had to replace its computers.",
    zh: "清空了石油公司沙特阿美约 3 万台计算机上的数据，用一张燃烧的美国国旗图片的一部分覆盖文件。这家公司不得不更换电脑。" },
  { year: 2013, name: "CryptoLocker", kind: "ransomware",
    en: "Encrypted victims' files and demanded payment in Bitcoin for the key. It spread through email attachments and the Gameover ZeuS botnet.",
    zh: "加密受害者的文件，索要比特币作为解密密钥的赎金。它通过邮件附件和 Gameover ZeuS 僵尸网络传播。" },
  { year: 2014, name: "Emotet", kind: "trojan",
    en: "Started as a banking Trojan and grew into a service that delivered other criminals' malware through booby-trapped email attachments.",
    zh: "起初是银行木马，后来发展成一项“服务”，通过带陷阱的邮件附件为其他犯罪分子投放恶意软件。" },
  { year: 2014, name: "Poweliks", kind: "fileless",
    en: "Hid its code in the Windows registry instead of in a file, and ran it through PowerShell, so antivirus scans looking for malicious files had nothing to find.",
    zh: "把代码藏在 Windows 注册表里而不是文件中，再通过 PowerShell 运行，让寻找恶意文件的杀毒扫描无从下手。" },
  { year: 2014, name: "Agent Tesla", kind: "keylogger",
    en: "Sold online as a \"monitoring tool\", it records keystrokes and steals passwords saved in browsers and email programs. It has stayed one of the most common pieces of malware in phishing emails for years.",
    zh: "在网上以“监控工具”的名义出售，它会记录按键并窃取浏览器和邮件程序中保存的密码。多年来它一直是钓鱼邮件中最常见的恶意软件之一。" },
  { year: 2016, name: "Mirai", kind: "bot",
    en: "Took over cameras and home routers still using factory-default passwords, building a botnet that knocked major websites offline in October 2016.",
    zh: "控制了仍在使用出厂默认密码的摄像头和家用路由器，组成僵尸网络，并在 2016 年 10 月让多个大型网站瘫痪。" },
  { year: 2017, name: "Fireball", kind: "adware",
    en: "Browser-hijacking adware bundled with free software. It changed people's home page and search engine to earn money from their browsing and could download more software; one security firm estimated 250 million infected computers.",
    zh: "捆绑在免费软件里的浏览器劫持广告软件。它会篡改主页和搜索引擎，从用户的浏览中牟利，还能下载更多软件；一家安全公司估计有 2.5 亿台电脑被感染。" },
  { year: 2017, name: "WannaCry", kind: "ransomware",
    en: "A ransomware worm that used the EternalBlue Windows flaw to infect more than 200,000 computers in 150 countries in May 2017, including UK hospitals.",
    zh: "一种勒索蠕虫，利用 Windows 的“永恒之蓝”漏洞，在 2017 年 5 月感染了 150 个国家的 20 多万台计算机，其中包括英国的医院。" },
  { year: 2017, name: "NotPetya", kind: "wiper",
    en: "Looked like ransomware but was built to destroy data: paying could not bring files back. It spread from a hijacked Ukrainian accounting-software update and caused billions of dollars of damage worldwide.",
    zh: "看起来像勒索软件，实际上是为了销毁数据而设计的：付了钱也拿不回文件。它通过一个被劫持的乌克兰会计软件更新传播，在全球造成数十亿美元的损失。" }
];

if (typeof module !== "undefined") { module.exports = { FW_HISTORY }; }
